### ISSUE TITLE
Create Docker images for ARM processors

### ISSUE THREAD

**Issue by McPringle** [McPringle/apus#83]

**Comment by McPringle** [comment]
Take a look at this example here:
https://github.com/ijug-ev/monika/blob/master/.github/workflows/build-and-deploy.yml

**Comment by eins78** [comment]
We tried building with [QEMU and buildx](https://github.com/docker/setup-qemu-action) and the emulation made the process very slow (after an hour it was still downloading dependencies). 

Because the build artefact is a platform independent jar, and the Dockerfile is a multi-stage build, a possible solution could be a 2-step build:
- build an intermediate image with the stage that produce the jar, using the the native platform
- build the images for all desired platforms by copying the jar in from the intermediate image.

See https://docs.docker.com/build/building/multi-stage/#use-an-external-image-as-a-stage
